# Generated by Django 5.1 on 2024-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sickstory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sickness",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end_date"),
        ),
    ]
